### ISSUE TITLE
I installed the dependencies, but I can't use Steemmonsters

### ISSUE THREAD

**Issue by CryptoSharon** [holgern/steemmonsters#8]
![image](https://user-images.githubusercontent.com/35318508/47887980-6fbc6880-de18-11e8-86f2-5f73ae32f3f1.png)

I can't leave with Ctrl+C (nothing happens, I have to close the window).

I installed the dependencies as is indicated (except beem, which I installed as [indicated in this issue](https://github.com/holgern/beem/issues/114)), and now when I try to run it, I don't have any errors but just nothing.

**Comment by CryptoSharon** [comment]
I had forgotten to set up Beem keys and Steemmonster config file and all. Still, Steemmonsters should respond instead of just staying all quiet and not letting me Ctrl + C.

**Comment by gitschwifty** [comment]
Was hoping this would be similar to my issue, but it looks like in the screenshot the whole thing hangs, since a prompt shows up once steemmonsters.py starts up. Probably an issue with not having the config set up, as when I tried to run with an incorrect config I got a couple second hang then a bunch of errors. Does it work now?

**Comment by holgern** [comment]
This is caused by scrypt  not properly installed:
```
pip install scrypt
```

**Comment by CryptoSharon** [comment]
I think that in the end this was caused by a bug in the interaction with Git Bash. I can't remember if I changed anything, but it works perfectly on Windows PowerShell.
